language: node_js
node_js:
  - "0.11"
install:
  - "npm install -g typescript"
  - "npm install -g closure-compiler"
script:
  - 'echo Compiling src/CDGDisplay.ts ...'
  - 'tsc -t "ES5" --declaration --out "build/CDGDisplay.js" "src/CDGDisplay.ts" --sourcemap'